import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import charactersRouter from "./characters.js";
import questsRouter from "./quests.js";
import leaderboardRouter from "./leaderboard.js";
import battleRouter from "./battle.js";
import inventoryRouter from "./inventory.js";
import cultivateRouter from "./cultivate.js";
import guildsRouter from "./guilds.js";
import narrativeRouter from "./narrative.js";
import memoriesRouter from "./memories.js";
import worldStateRouter from "./worldState.js";
import skillsRouter from "./skills.js";
import factionsRouter from "./factions.js";
import marketRouter from "./market.js";
import worldEventsRouter from "./worldEvents.js";
import npcsRouter from "./npcs.js";
import worldCreatorRouter from "./worldCreator.js";
import multiverseRouter from "./multiverse.js";
import pvpRouter from "./pvp.js";
import achievementsRouter from "./achievements.js";
import dailyRouter from "./daily.js";
import dungeonRouter from "./dungeon.js";
import craftRouter from "./craft.js";
import guildWarRouter from "./guildWar.js";
import feedRouter from "./feed.js";
import godModeRouter from "./godMode.js";
import worldTradeRouter from "./worldTrade.js";
import worldPassportRouter from "./worldPassport.js";
import prophecyRouter from "./prophecy.js";
import isekaiRouter from "./isekai.js";
import fateRouter from "./fate.js";
import notificationsRouter from "./notifications.js";
import passwordResetRouter from "./passwordReset.js";
import emailVerificationRouter from "./emailVerification.js";
import auctionRouter from "./auction.js";
import titlesRouter from "./titles.js";
import petsRouter from "./pets.js";
import worldEconomyRouter from "./worldEconomy.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(charactersRouter);
router.use(questsRouter);
router.use(leaderboardRouter);
router.use(battleRouter);
router.use(inventoryRouter);
router.use(cultivateRouter);
router.use(guildsRouter);
router.use(narrativeRouter);
router.use(memoriesRouter);
router.use(worldStateRouter);
router.use(skillsRouter);
router.use(factionsRouter);
router.use(marketRouter);
router.use(worldEventsRouter);
router.use(npcsRouter);
router.use(worldCreatorRouter);
router.use(multiverseRouter);
router.use(pvpRouter);
router.use(achievementsRouter);
router.use(dailyRouter);
router.use(dungeonRouter);
router.use(craftRouter);
router.use(guildWarRouter);
router.use(feedRouter);
router.use(godModeRouter);
router.use(worldTradeRouter);
router.use(worldPassportRouter);
router.use(prophecyRouter);
router.use(isekaiRouter);
router.use(fateRouter);
router.use(notificationsRouter);
router.use(passwordResetRouter);
router.use(emailVerificationRouter);
router.use(auctionRouter);
router.use(titlesRouter);
router.use(petsRouter);
router.use(worldEconomyRouter);

export default router;
