import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import charactersRouter from "./characters.js";
import questsRouter from "./quests.js";
import leaderboardRouter from "./leaderboard.js";
import battleRouter from "./battle.js";
import inventoryRouter from "./inventory.js";
import cultivateRouter from "./cultivate.js";
import guildsRouter from "./guilds.js";
import narrativeRouter from "./narrative.js";
import memoriesRouter from "./memories.js";
import worldStateRouter from "./worldState.js";
import skillsRouter from "./skills.js";
import factionsRouter from "./factions.js";
import marketRouter from "./market.js";
import worldEventsRouter from "./worldEvents.js";
import npcsRouter from "./npcs.js";
import worldCreatorRouter from "./worldCreator.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(charactersRouter);
router.use(questsRouter);
router.use(leaderboardRouter);
router.use(battleRouter);
router.use(inventoryRouter);
router.use(cultivateRouter);
router.use(guildsRouter);
router.use(narrativeRouter);
router.use(memoriesRouter);
router.use(worldStateRouter);
router.use(skillsRouter);
router.use(factionsRouter);
router.use(marketRouter);
router.use(worldEventsRouter);
router.use(npcsRouter);
router.use(worldCreatorRouter);

export default router;
